In [25]:
from kafka import KafkaProducer
import json
import time

# Initialize Kafka producer
producer = KafkaProducer(
    bootstrap_servers='localhost:9092',
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
)

In [26]:
import pandas as pd 
loan_application = pd.read_csv("/home/drissdo/Desktop/Scalable-Distributed-Systems/data/Loan_default.csv")

In [27]:
loan_applications = loan_application.sample(32)[:20].drop("Default",axis=1)

In [32]:
loan_applications

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
229163,PI84WFJA16,18,144905,229417,843,20,3,10.58,12,0.19,PhD,Self-employed,Married,No,No,Home,No
10292,Q47SC11GPK,40,81838,94296,678,112,1,9.09,36,0.10,Bachelor's,Self-employed,Divorced,Yes,No,Other,No
113317,5PKRDS9T6G,51,101410,23748,661,63,1,22.64,24,0.14,High School,Unemployed,Married,Yes,No,Business,No
74251,DT0Q970YGH,39,55621,174609,752,85,1,9.69,60,0.56,Master's,Full-time,Single,No,No,Other,No
84532,A38RC479WR,59,132651,97786,336,63,4,14.94,48,0.22,PhD,Part-time,Single,Yes,Yes,Business,Yes
20174,CRDXTPI8KY,29,118525,143289,521,92,1,20.70,48,0.15,PhD,Self-employed,Married,Yes,No,Business,Yes
169133,V5L1T406JF,22,113680,249505,790,97,3,16.04,48,0.58,High School,Self-employed,Married,Yes,Yes,Other,Yes
161798,P3EG7LBMIC,54,37387,239689,814,32,1,7.45,24,0.32,Bachelor's,Full-time,Married,No,No,Education,Yes
83698,0HCI1B2YTB,25,93593,234785,359,20,1,23.40,60,0.74,PhD,Part-time,Married,No,Yes,Other,No
5040,BV6I61ZH8K,66,135744,42609,570,50,4,15.00,12,0.42,High School,Part-time,Married,No,Yes,Other,No
7728,8LX0LK8Y7J,67,75817,66512,520,38,4,17.76,24,0.86,High School,Unemployed,Divorced,No,No,Other,No
61176,UMJ25ZD6PX,20,47039,112301,496,83,2,17.69,48,0.84,High School,Unemployed,Single,No,Yes,Education,No
230414,VHVCKK7F25,23,48726,31268,598,80,3,14.18,24,0.79,High School,Unemployed,Divorced,No,No,Auto,No
176408,XN2FOKJ26P,35,114197,145148,834,26,3,17.97,24,0.85,PhD,Full-time,Divorced,Yes,No,Other,Yes
204680,BB9FDTKPFE,66,127228,203921,304,75,1,9.30,60,0.20,Master's,Part-time,Divorced,Yes,Yes,Home,No
24367,0HOJTGKRZS,58,28520,18087,684,50,2,12.84,36,0.79,PhD,Unemployed,Single,Yes,Yes,Auto,No
16479,6XW7VHV3DZ,42,21311,26711,326,51,3,10.29,60,0.60,High School,Unemployed,Divorced,Yes,Yes,Education,No
177292,3AU7U4IKEO,34,145034,240768,599,33,3,16.85,36,0.17,Bachelor's,Self-employed,Married,Yes,No,Other,No
150163,EXENZ2QVJX,59,119985,193887,580,117,3,11.09,12,0.72,Bachelor's,Part-time,Single,No,No,Education,No
198853,49BYIQJMSN,34,65913,85006,404,59,1,23.23,24,0.27,Bachelor's,Unemployed,Single,No,Yes,Auto,No

In [50]:
topic ="loan_applications"
for _, row in loan_applications.iterrows():
    message = row.to_dict()  # Convert row to dictionary
    producer.send(topic, value=message)  # Send the message
    print(f"Sent: {message}")

Sent: {'LoanID': 'PI84WFJA16', 'Age': 18, 'Income': 144905, 'LoanAmount': 229417, 'CreditScore': 843, 'MonthsEmployed': 20, 'NumCreditLines': 3, 'InterestRate': 10.58, 'LoanTerm': 12, 'DTIRatio': 0.19, 'Education': 'PhD', 'EmploymentType': 'Self-employed', 'MaritalStatus': 'Married', 'HasMortgage': 'No', 'HasDependents': 'No', 'LoanPurpose': 'Home', 'HasCoSigner': 'No'}
Sent: {'LoanID': 'Q47SC11GPK', 'Age': 40, 'Income': 81838, 'LoanAmount': 94296, 'CreditScore': 678, 'MonthsEmployed': 112, 'NumCreditLines': 1, 'InterestRate': 9.09, 'LoanTerm': 36, 'DTIRatio': 0.1, 'Education': "Bachelor's", 'EmploymentType': 'Self-employed', 'MaritalStatus': 'Divorced', 'HasMortgage': 'Yes', 'HasDependents': 'No', 'LoanPurpose': 'Other', 'HasCoSigner': 'No'}
Sent: {'LoanID': '5PKRDS9T6G', 'Age': 51, 'Income': 101410, 'LoanAmount': 23748, 'CreditScore': 661, 'MonthsEmployed': 63, 'NumCreditLines': 1, 'InterestRate': 22.64, 'LoanTerm': 24, 'DTIRatio': 0.14, 'Education': 'High School', 'EmploymentType': 'Unemployed', 'MaritalStatus': 'Married', 'HasMortgage': 'Yes', 'HasDependents': 'No', 'LoanPurpose': 'Business', 'HasCoSigner': 'No'}
Sent: {'LoanID': 'DT0Q970YGH', 'Age': 39, 'Income': 55621, 'LoanAmount': 174609, 'CreditScore': 752, 'MonthsEmployed': 85, 'NumCreditLines': 1, 'InterestRate': 9.69, 'LoanTerm': 60, 'DTIRatio': 0.56, 'Education': "Master's", 'EmploymentType': 'Full-time', 'MaritalStatus': 'Single', 'HasMortgage': 'No', 'HasDependents': 'No', 'LoanPurpose': 'Other', 'HasCoSigner': 'No'}
Sent: {'LoanID': 'A38RC479WR', 'Age': 59, 'Income': 132651, 'LoanAmount': 97786, 'CreditScore': 336, 'MonthsEmployed': 63, 'NumCreditLines': 4, 'InterestRate': 14.94, 'LoanTerm': 48, 'DTIRatio': 0.22, 'Education': 'PhD', 'EmploymentType': 'Part-time', 'MaritalStatus': 'Single', 'HasMortgage': 'Yes', 'HasDependents': 'Yes', 'LoanPurpose': 'Business', 'HasCoSigner': 'Yes'}
Sent: {'LoanID': 'CRDXTPI8KY', 'Age': 29, 'Income': 118525, 'LoanAmount': 143289, 'CreditScore': 521, 'MonthsEmployed': 92, 'NumCreditLines': 1, 'InterestRate': 20.7, 'LoanTerm': 48, 'DTIRatio': 0.15, 'Education': 'PhD', 'EmploymentType': 'Self-employed', 'MaritalStatus': 'Married', 'HasMortgage': 'Yes', 'HasDependents': 'No', 'LoanPurpose': 'Business', 'HasCoSigner': 'Yes'}
Sent: {'LoanID': 'V5L1T406JF', 'Age': 22, 'Income': 113680, 'LoanAmount': 249505, 'CreditScore': 790, 'MonthsEmployed': 97, 'NumCreditLines': 3, 'InterestRate': 16.04, 'LoanTerm': 48, 'DTIRatio': 0.58, 'Education': 'High School', 'EmploymentType': 'Self-employed', 'MaritalStatus': 'Married', 'HasMortgage': 'Yes', 'HasDependents': 'Yes', 'LoanPurpose': 'Other', 'HasCoSigner': 'Yes'}
Sent: {'LoanID': 'P3EG7LBMIC', 'Age': 54, 'Income': 37387, 'LoanAmount': 239689, 'CreditScore': 814, 'MonthsEmployed': 32, 'NumCreditLines': 1, 'InterestRate': 7.45, 'LoanTerm': 24, 'DTIRatio': 0.32, 'Education': "Bachelor's", 'EmploymentType': 'Full-time', 'MaritalStatus': 'Married', 'HasMortgage': 'No', 'HasDependents': 'No', 'LoanPurpose': 'Education', 'HasCoSigner': 'Yes'}
Sent: {'LoanID': '0HCI1B2YTB', 'Age': 25, 'Income': 93593, 'LoanAmount': 234785, 'CreditScore': 359, 'MonthsEmployed': 20, 'NumCreditLines': 1, 'InterestRate': 23.4, 'LoanTerm': 60, 'DTIRatio': 0.74, 'Education': 'PhD', 'EmploymentType': 'Part-time', 'MaritalStatus': 'Married', 'HasMortgage': 'No', 'HasDependents': 'Yes', 'LoanPurpose': 'Other', 'HasCoSigner': 'No'}
Sent: {'LoanID': 'BV6I61ZH8K', 'Age': 66, 'Income': 135744, 'LoanAmount': 42609, 'CreditScore': 570, 'MonthsEmployed': 50, 'NumCreditLines': 4, 'InterestRate': 15.0, 'LoanTerm': 12, 'DTIRatio': 0.42, 'Education': 'High School', 'EmploymentType': 'Part-time', 'MaritalStatus': 'Married', 'HasMortgage': 'No', 'HasDependents': 'Yes', 'LoanPurpose': 'Other', 'HasCoSigner': 'No'}
Sent: {'LoanID': '8LX0LK8Y7J', 'Age': 67, 'Income': 75817, 'LoanAmount': 66512, 'CreditScore': 520, 'MonthsEmployed': 38, 'NumCreditLines': 4, 'InterestRate': 17.76, 'LoanTerm': 24, 'DTIRatio': 0.86, 'Education': 'High School', 'EmploymentType': 'Unemployed', 'MaritalStatus': 'Divorced', 'HasMortgage': 'No', 'HasDependents': 'No', 'LoanPurpose': 'Other', 'HasCoSigner': 'No'}
Sent: {'LoanID': 'UMJ25ZD6PX', 'Age': 20, 'Income': 47039, 'LoanAmount': 112301, 'CreditScore': 496, 'MonthsEmployed': 83, 'NumCreditLines': 2, 'InterestRate': 17.69, 'LoanTerm': 48, 'DTIRatio': 0.84, 'Education': 'High School', 'EmploymentType': 'Unemployed', 'MaritalStatus': 'Single', 'HasMortgage': 'No', 'HasDependents': 'Yes', 'LoanPurpose': 'Education', 'HasCoSigner': 'No'}
Sent: {'LoanID': 'VHVCKK7F25', 'Age': 23, 'Income': 48726, 'LoanAmount': 31268, 'CreditScore': 598, 'MonthsEmployed': 80, 'NumCreditLines': 3, 'InterestRate': 14.18, 'LoanTerm': 24, 'DTIRatio': 0.79, 'Education': 'High School', 'EmploymentType': 'Unemployed', 'MaritalStatus': 'Divorced', 'HasMortgage': 'No', 'HasDependents': 'No', 'LoanPurpose': 'Auto', 'HasCoSigner': 'No'}
Sent: {'LoanID': 'XN2FOKJ26P', 'Age': 35, 'Income': 114197, 'LoanAmount': 145148, 'CreditScore': 834, 'MonthsEmployed': 26, 'NumCreditLines': 3, 'InterestRate': 17.97, 'LoanTerm': 24, 'DTIRatio': 0.85, 'Education': 'PhD', 'EmploymentType': 'Full-time', 'MaritalStatus': 'Divorced', 'HasMortgage': 'Yes', 'HasDependents': 'No', 'LoanPurpose': 'Other', 'HasCoSigner': 'Yes'}
Sent: {'LoanID': 'BB9FDTKPFE', 'Age': 66, 'Income': 127228, 'LoanAmount': 203921, 'CreditScore': 304, 'MonthsEmployed': 75, 'NumCreditLines': 1, 'InterestRate': 9.3, 'LoanTerm': 60, 'DTIRatio': 0.2, 'Education': "Master's", 'EmploymentType': 'Part-time', 'MaritalStatus': 'Divorced', 'HasMortgage': 'Yes', 'HasDependents': 'Yes', 'LoanPurpose': 'Home', 'HasCoSigner': 'No'}
Sent: {'LoanID': '0HOJTGKRZS', 'Age': 58, 'Income': 28520, 'LoanAmount': 18087, 'CreditScore': 684, 'MonthsEmployed': 50, 'NumCreditLines': 2, 'InterestRate': 12.84, 'LoanTerm': 36, 'DTIRatio': 0.79, 'Education': 'PhD', 'EmploymentType': 'Unemployed', 'MaritalStatus': 'Single', 'HasMortgage': 'Yes', 'HasDependents': 'Yes', 'LoanPurpose': 'Auto', 'HasCoSigner': 'No'}
Sent: {'LoanID': '6XW7VHV3DZ', 'Age': 42, 'Income': 21311, 'LoanAmount': 26711, 'CreditScore': 326, 'MonthsEmployed': 51, 'NumCreditLines': 3, 'InterestRate': 10.29, 'LoanTerm': 60, 'DTIRatio': 0.6, 'Education': 'High School', 'EmploymentType': 'Unemployed', 'MaritalStatus': 'Divorced', 'HasMortgage': 'Yes', 'HasDependents': 'Yes', 'LoanPurpose': 'Education', 'HasCoSigner': 'No'}
Sent: {'LoanID': '3AU7U4IKEO', 'Age': 34, 'Income': 145034, 'LoanAmount': 240768, 'CreditScore': 599, 'MonthsEmployed': 33, 'NumCreditLines': 3, 'InterestRate': 16.85, 'LoanTerm': 36, 'DTIRatio': 0.17, 'Education': "Bachelor's", 'EmploymentType': 'Self-employed', 'MaritalStatus': 'Married', 'HasMortgage': 'Yes', 'HasDependents': 'No', 'LoanPurpose': 'Other', 'HasCoSigner': 'No'}
Sent: {'LoanID': 'EXENZ2QVJX', 'Age': 59, 'Income': 119985, 'LoanAmount': 193887, 'CreditScore': 580, 'MonthsEmployed': 117, 'NumCreditLines': 3, 'InterestRate': 11.09, 'LoanTerm': 12, 'DTIRatio': 0.72, 'Education': "Bachelor's", 'EmploymentType': 'Part-time', 'MaritalStatus': 'Single', 'HasMortgage': 'No', 'HasDependents': 'No', 'LoanPurpose': 'Education', 'HasCoSigner': 'No'}
Sent: {'LoanID': '49BYIQJMSN', 'Age': 34, 'Income': 65913, 'LoanAmount': 85006, 'CreditScore': 404, 'MonthsEmployed': 59, 'NumCreditLines': 1, 'InterestRate': 23.23, 'LoanTerm': 24, 'DTIRatio': 0.27, 'Education': "Bachelor's", 'EmploymentType': 'Unemployed', 'MaritalStatus': 'Single', 'HasMortgage': 'No', 'HasDependents': 'Yes', 'LoanPurpose': 'Auto', 'HasCoSigner': 'No'}

In [51]:
producer.close()